const esc = (value) => String(value ?? "—").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const list = (items) => items.length ? `<ul>${items.map((item) => `<li>${esc(item)}</li>`).join("")}</ul>` : "<p>None triggered; more farm input is needed.</p>";

export function renderStrategies(strategies, sourceMap) {
  document.getElementById("strategies").innerHTML = strategies.map((strategy) => {
    const dataSourceIds = [strategy.indicators.historicalRainMm !== null && "nasa-power-daily", strategy.indicators.satellitePrecipitation && "nasa-gpm-imerg", strategy.soil && "usda-ssurgo"].filter(Boolean);
    const sourceIds = [...new Set([...strategy.evidence.flatMap((evidence) => evidence.sourceIds), ...dataSourceIds])];
    const sources = sourceIds.map((id) => sourceMap.get(id)).filter(Boolean);
    const nasa = [`POWER historical rainfall: ${strategy.indicators.historicalRainMm === null ? "missing" : strategy.indicators.historicalRainMm.toFixed(0) + " mm"}`, `POWER hot days (max ≥30°C): ${strategy.indicators.historicalHotDays30C ?? "missing"}`, `IMERG matched-day rainfall: ${strategy.indicators.satellitePrecipitation ? strategy.indicators.satellitePrecipitation.value.toFixed(1) + " mm on " + strategy.indicators.satellitePrecipitation.time : "missing"}`];
    return `<article class="strategy-card"><span class="strategy-kicker">${esc(strategy.label)}</span><h3>${esc(strategy.title)}</h3><p>${esc(strategy.description)}</p><div class="sequence">${strategy.sequence.map((crop) => `<span>${esc(crop.commonName)}</span>`).join("<b>→</b>")}</div><p class="confidence-badge">Confidence: ${esc(strategy.confidence.level)} · Human-approved: no</p><details class="why-panel"><summary>Why this strategy?</summary><div class="why-content"><h4>Farmer inputs used</h4><p>Last crop: ${esc(strategy.inputUsed.lastCrop)}; prior crop: ${esc(strategy.inputUsed.priorCrop)}; priorities: ${esc(strategy.inputUsed.priorities.join(", ") || "none")}; farmer texture note: ${esc(strategy.inputUsed.soilTexture)}; lab pH: ${esc(strategy.inputUsed.soilPh)}. Texture and pH are displayed but do not trigger an unreviewed suitability threshold.</p><h4>NASA variables used</h4>${list(nasa)}<h4>Mapped soil used</h4><p>${strategy.soil ? `${esc(strategy.soil.mapUnit.symbol)} ${esc(strategy.soil.mapUnit.name)}; possible components: ${esc(strategy.soil.possibleComponents.join(", "))}.` : "SSURGO not loaded."}</p><h4>Research matches (not approved)</h4>${list(strategy.rules.map((rule) => `${rule.id}: ${rule.positiveConsideration} Human approval: ${rule.humanApproved ? "yes" : "no"}.`))}<h4>Potential benefits</h4>${list(strategy.benefits)}<h4>Possible risks</h4>${list(strategy.risks)}<h4>Evidence and data sources</h4>${list(strategy.evidence.map((item) => `${item.id}: ${item.claim} (${item.confidence}; ${item.limitations})`))}<p>${sources.map((source) => `<a href="${esc(source.url)}" target="_blank" rel="noreferrer">${esc(source.name)} ↗</a>`).join(" · ") || "No linked source for currently triggered rules."}</p><h4>Missing and uncertainty</h4>${list([...strategy.missing, ...strategy.confidence.reasons])}<h4>Confirm locally</h4>${list(strategy.localChecks)}</div></details></article>`;
  }).join("");
}
